### ISSUE TITLE
Cross Project Collaboration

### ISSUE THREAD

**Issue by scottbyrns** [PlanTeam/PlanTCP#1]
I want to invite you folks to take a look at https://github.com/SwiftX/C7/

It's a group working on cross project standard protocols to enable us all to build libraries that are interoperable.

For example I just updated a very similar TCP library to your own to conform to the C7 protocols.
https://github.com/VeniceX/TCP/tree/TCPConnection

If you were to do the same your library could be substituted for ours at any point.

The C7 standards are mutable and we welcome input on what the protocols should be and what should be added or removed. Would love to have you join the community.

Thanks!

**Comment by Obbut** [comment]
Thanks, but we already participate with for example [BSON](https://github.com/PlanTeam/BSON). We have created this library early in the development of [MongoKitten](https://github.com/PlanTeam/MongoKitten), but don't use or support this library actively anymore.

Still, thanks for the issue! I'll close it, and maybe next week update the readme to make it more clear that this library isn't used anymore.
